use blinkit;
select * from blinkit_data;
select count(*) from blinkit_data;
SELECT DISTINCT(item_fat_content) from blinkit_data;

UPDATE BLINKIT_DATA
SET ITEM_FAT_CONTENT = 
CASE
WHEN ITEM_FAT_CONTENT IN ("low fat","LF") THEN ("Low Fat")
WHEN ITEM_FAT_CONTENT = "reg" then ("Regular")
ELSE ITEM_FAT_CONTENT END;

-- TOTAL SALES
SELECT SUM(SALES) FROM BLINKIT_DATA;
SELECT CAST(SUM(SALES)/1000000.0 AS DECIMAL (10,2))AS TOTAL_MILLION_SALES
 FROM BLINKIT_DATA;

-- AVERAGE SALES
SELECT AVG(SALES) FROM BLINKIT_DATA;
SELECT CAST(AVG(SALES) AS DECIMAL(10,0))AS AVG_SALES
FROM BLINKIT_DATA;

-- NO.OF ITEMS SOLD
SELECT DISTINCT COUNT(*) FROM blinkit_data;

-- AVERAGE RATING

SELECT CAST(AVG(RATING) AS DECIMAL (10,1))AS AVG_RATING
 FROM blinkit_data
WHERE Outlet_Establishment_Year =2012;

--- TOTALS SALES BY FAT CONTENT

SELECT * FROM blinkit_data;
SELECT ITEM_FAT_CONTENT,
CAST(SUM(SALES) AS DECIMAL(10,2))AS TOTAL_SALES,
CAST(AVG(SALES) AS DECIMAL (10,0)) AS AVERAGE_SALES,
CAST(COUNT(*) AS DECIMAL (10,0)) AS TOTAL_ORDERS,
CAST(AVG(RATING) AS DECIMAL (10,0)) AS AVERAGE_RATING
FROM blinkit_data
group by Item_Fat_Content
ORDER BY Item_Fat_Content ;

---- TOTALS SALES BY ITEM TYPE
SELECT ITEM_TYPE,
CAST(SUM(SALES) AS DECIMAL (10,0)) AS TOTAL_SALES,
CAST(AVG(SALES) AS DECIMAL (10,2)) AS AVERAGE_SALES,
CAST(COUNT(*) AS DECIMAL (10,0)) AS TOTAL_ORDERS,
CAST(AVG(RATING) AS DECIMAL (10,2)) AS AVERAGE_RATING
FROM BLINKIT_DATA
GROUP BY ITEM_TYPE
ORDER BY ITEM_TYPE
limit 5;

SELECT * FROM blinkit_data;
SELECT *,
row_number() OVER(PARTITION BY OUTLET_LOCATION_TYPE ORDER BY TOTAL_SALES DESC) AS SALES_RNK
FROM
(SELECT Outlet_Location_Type,ITEM_FAT_CONTENT,
CAST(SUM(SALES) AS DECIMAL(10,2))AS TOTAL_SALES
FROM blinkit_data
group by Outlet_Location_Type,Item_Fat_Content) AS T
ORDER BY Item_Fat_Content ;

SELECT *,
RANK() OVER (PARTITION BY outlet_LOCATION_TYPE ORDER BY total_sales DESC) AS sales_rank
FROM (
    SELECT 
        outlet_LOCATION_TYPE,
        ITEM_fat_content,
        SUM(sales) AS total_sales,
        AVG(sales) AS avg_sales,
        COUNT(*) AS number_of_items,
        AVG(rating) AS avg_rating
    FROM blinkit_DATA
    GROUP BY outlet_LOCATION_TYPE, ITEM_fat_content
) t;


SELECT 
    outlet_LOCATION_TYPE,
    CAST(SUM(CASE WHEN item_fat_content = 'Low Fat' THEN sales ELSE 0 END)AS DECIMAL(10,2)) AS low_fat_sales,
	CAST(SUM(CASE WHEN item_fat_content = 'Regular' THEN sales ELSE 0 END)AS DECIMAL(10,2)) AS regular_sales
FROM blinkit_data
GROUP BY outlet_LOCATION_TYPE;

select OUTLET_LOCATION_TYPE,
	CAST(SUM(CASE WHEN ITEM_FAT_CONTENT="LOW FAT" THEN SALES ELSE 0 END)AS DECIMAL(10,2)) AS LOW_FAT_SALES,
    CAST(SUM(CASE WHEN ITEM_FAT_CONTENT="REGULAR" THEN SALES ELSE 0 END)AS DECIMAL (10,2)) AS REGULAR_SALES
FROM BLINKIT_DATA
GROUP BY OUTLET_LOCATION_TYPE;


-- OUTLET YEAR SALES
SELECT distinct(OUTLET_ESTABLISHMENT_YEAR) FROM BLINKIT_DATA;
select * from blinkit_data;
SELECT OUTLET_ESTABLISHMENT_YEAR,CAST(SUM(SALES) AS DECIMAL(10,2)) AS TOTAL_SALES
FROM BLINKIT_DATA
GROUP BY OUTLET_ESTABLISHMENT_YEAR
ORDER BY OUTLET_ESTABLISHMENT_YEAR;		

---- SALES PERCENTAGE OF OUTLET TYPE
SELECT OUTLET_SIZE,
	CAST(SUM(SALES) AS DECIMAL(10,2)) AS TOTAL_SALES,
    CAST(SUM(SALES)*100/SUM(SUM(SALES)) OVER() AS DECIMAL(10,2)) AS PERCENTAGE_SALES
FROM BLINKIT_DATA
GROUP BY OUTLET_SIZE;

--- SALES OF OUTET LOCATION
SELECT OUTLET_LOCATION_TYPE,
	CAST(SUM(SALES) AS DECIMAL(10,2)) AS TOTAL_SALES
FROM BLINKIT_DATA
GROUP BY OUTLET_LOCATION_TYPE;

--- ALL METRICS OF OUTLET TYPE
SELECT OUTLET_TYPE,
CAST(SUM(SALES) AS DECIMAL(10,2))AS TOTAL_SALES,
CAST(AVG(SALES) AS DECIMAL (10,2)) AS AVERAGE_SALES,
CAST(COUNT(*) AS DECIMAL (10,0)) AS TOTAL_ORDERS,
CAST(AVG(RATING) AS DECIMAL (10,2)) AS AVERAGE_RATING,
CAST(AVG(Item_Visibility) AS DECIMAL(10,2)) AS AVERAGE_VISBILITY
FROM blinkit_data
group by OUTLET_TYPE
ORDER BY OUTLET_TYPE;

--- PERCENTAGE OF SALES BY OUTLET SIZE

SELECT OUTLET_SIZE,
CAST(SUM(SALES) AS DECIMAL (10,0)) AS TOTAL_SALES,
CAST(SUM(SALES)*100/SUM(SUM(SALES)) AS DECIMAL (10,2)) AS PERCENTAGE_SALES
FROM BLINKIT_DATA

 
SELECT OUTLET_SIZE,
	CAST(SUM(SALES) AS DECIMAL(10,2)) AS TOTAL_SALES,
    CAST(SUM(SALES)*100/SUM(SUM(SALES)) OVER() AS DECIMAL(10,2)) AS PERCENTAGE_SALES
FROM BLINKIT_DATA
GROUP BY OUTLET_SIZE;






